notifications:
  email:
    recipients:
      - groonga-commit@lists.osdn.me

language: cpp

sudo: required

services:
  - docker

matrix:
  include:
    - os: linux
      compiler: gcc
      env: BUILD_TOOL=autotools
    - os: linux
      compiler: gcc
      env: BUILD_TOOL=autotools ENABLE_MRUBY=yes
    - os: linux
      compiler: gcc
      env: BUILD_TOOL=autotools CFLAGS=-funsigned-char CXXFLAGS=-funsigned-char
    - os: linux
      compiler: gcc
      env: BUILD_TOOL=cmake
    - os: linux
      compiler: gcc
      env: BUILD_TOOL=cmake ENABLE_MRUBY=yes
    - os: linux
      compiler: clang
      env: BUILD_TOOL=autotools ENABLE_MRUBY=yes
    - os: linux
      compiler: clang
      env: BUILD_TOOL=cmake ENABLE_MRUBY=yes
    - os: osx
      compiler: clang
      env: BUILD_TOOL=autotools ENABLE_MRUBY=yes TEST_TARGET=command
    - os: osx
      compiler: clang
      env: BUILD_TOOL=autotools ENABLE_MRUBY=yes TEST_TARGET=command-http
    - os: osx
      compiler: clang
      env: BUILD_TOOL=autotools ENABLE_MRUBY=yes TEST_TARGET=command-httpd
    - os: osx
      compiler: clang
      env: BUILD_TOOL=cmake ENABLE_MRUBY=yes
    - os: linux
      env: DOCKER=ubuntu-14.04
    - os: linux
      env: DOCKER=ubuntu-16.04
    - os: linux
      env: DOCKER=ubuntu-18.04
    - os: linux
      env: TARGET=windows ARCHITECTURES=x86
    - os: linux
      env: TARGET=windows ARCHITECTURES=x64
  allow_failures:
  #   - os: osx
  #     compiler: clang
  #     env: BUILD_TOOL=autotools ENABLE_MRUBY=yes
    - os: linux
      env: TARGET=windows ARCHITECTURES=x86
    - os: linux
      env: TARGET=windows ARCHITECTURES=x64

before_install:
  # - rvm use 2.3.1 --install --binary --fuzzy
  # - rvm use 2.2
  - gem update bundler

install:
  - travis/install.sh

before_script:
  - travis/before-script.sh

script:
  - travis/script.sh
