notifications:
  email:
    recipients:
      - groonga-commit@lists.sourceforge.jp
language: cpp
matrix:
  include:
    - os: linux
      compiler: gcc
      env: BUILD_TOOL=autotools
    - os: linux
      compiler: gcc
      env: BUILD_TOOL=autotools ENABLE_RUBY=yes
    - os: linux
      compiler: gcc
      env: BUILD_TOOL=autotools CFLAGS=-funsigned-char CXXFLAGS=-funsigned-char
    - os: linux
      compiler: gcc
      env: BUILD_TOOL=cmake
    - os: linux
      compiler: gcc
      env: BUILD_TOOL=cmake ENABLE_RUBY=yes
    - os: linux
      compiler: clang
      env: BUILD_TOOL=autotools ENABLE_RUBY=yes
    - os: linux
      compiler: clang
      env: BUILD_TOOL=cmake ENABLE_RUBY=yes
    - os: osx
      compiler: gcc
      env: BUILD_TOOL=autotools ENABLE_RUBY=yes
    - os: osx
      compiler: clang
      env: BUILD_TOOL=cmake ENABLE_RUBY=yes
before_install:
  - rvm use 2.1
install:
  - tools/travis-install.sh
before_script:
  - tools/travis-before-script.sh
script:
  - tools/travis-script.sh
