version: "{build}"
clone_depth: 10

environment:
  matrix:
    - CMAKE_GENERATOR_NAME: "Visual Studio 12 2013"
      VC_INIT: C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat
      VC_MACHINE: x86
    - CMAKE_GENERATOR_NAME: "Visual Studio 12 2013 Win64"
      VC_INIT: C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat
      VC_MACHINE: amd64
    - CMAKE_GENERATOR_NAME: "Visual Studio 14 2015"
      VC_INIT: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat
      VC_MACHINE: x86
    - CMAKE_GENERATOR_NAME: "Visual Studio 14 2015 Win64"
      VC_INIT: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat
      VC_MACHINE: amd64

notifications:
  - provider: Email
    to:
      - groonga-commit@lists.osdn.me
    on_build_status_changed: true

init:
  - call "%VC_INIT%" %VC_MACHINE%
  - set PATH=C:\Ruby22\bin;%PATH%
  - set PATH=C:\msys64\usr\bin;%PATH%
#  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
  - tzutil /s "Tokyo Standard Time"
  # - choco install -y imdisk-toolkit
  # - mkdir tmp
  # - imdisk -a -t file -m tmp -o awe -s 1G -p "/fs:ntfs /q /y"

build_script:
  - git submodule update --init
  - cd vendor
  - ruby download_mecab.rb
  - ruby download_message_pack.rb
  - ruby download_lz4.rb
  - cd ..
  - cmake . -G "%CMAKE_GENERATOR_NAME%"
      -DCMAKE_INSTALL_PREFIX=c:\groonga
      -DGRN_WITH_MRUBY=yes
      -DGRN_WITH_BUNDLED_MECAB=yes
      -DGRN_WITH_BUNDLED_MESSAGE_PACK=yes
      -DGRN_WITH_BUNDLED_LZ4=yes
  - cmake --build . --config Debug
  - cmake --build . --config Debug --target Install

before_test:
  - git clone --depth 1
      https://github.com/groonga/grntest.git
      test\command\grntest
  - cd test\command\grntest
  - bundle install --binstubs=..\bin
  - cd ..\..\..
test_script:
  - ruby test\command\bin\grntest
     --groonga c:\groonga\bin\groonga.exe
     --base-directory test\command
     --reporter mark
     --n-workers 1
     --timeout 60
     test\command\suite
