version: "{build}"
clone_depth: 10

platform:
  - x86
  - x64

notifications:
  - provider: Email
    to:
      - kou@clear-code.com
      - groonga-commit@lists.osdn.me
    on_build_status_changed: true

install:
  - tzutil /s "Tokyo Standard Time"
  # - choco install -y imdisk-toolkit
  # - mkdir tmp
  # - imdisk -a -t file -m tmp -o awe -s 512M -p "/fs:ntfs /q /y"

build_script:
  - ps: |
      if ($Env:PLATFORM -eq "x86")
      {
        $Env:PATH = "C:\Ruby22\bin;$Env:PATH"
        $Env:CMAKE_GENERATOR_NAME = "Visual Studio 12 2013"
      }
      else
      {
        $Env:PATH = "C:\Ruby22-x64\bin;$Env:PATH"
        $Env:CMAKE_GENERATOR_NAME = "Visual Studio 12 2013 Win64"
      }
  - git submodule update --init
  - cd vendor
  - ruby download_mecab.rb
  - cd ..
  - |
      cmake . ^
        -G "%CMAKE_GENERATOR_NAME%" ^
        -DCMAKE_INSTALL_PREFIX=c:\groonga ^
        -DGRN_WITH_BUNDLED_MECAB=yes
  - cmake --build . --config Debug
  - cmake --build . --config Debug --target Install

before_test:
  - gem install grntest
test_script:
  - SET GRN_QUERY_EXPANDER_TSV_SYNONYMS_FILE=%APPVEYOR_BUILD_FOLDER%\test\command\tmp\synonyms.tsv
  - grntest --groonga c:\groonga\bin\groonga.exe --base-directory test\command --reporter stream --debug test\command\suite\schema
