version: "{build}"
clone_depth: 10

platform:
  - x86
  - x64

notifications:
  - provider: Email
    to:
      - kou@clear-code.com
      - groonga-commit@lists.osdn.me
    on_build_status_changed: true

build_script:
  - ps: |
      if ($Env:PLATFORM -eq "x86")
      {
        $Env:PATH = "C:\Ruby22\bin;$Env:PATH"
        $Env:CMAKE_GENERATOR_NAME = "Visual Studio 12 2013"
      }
      else
      {
        $Env:PATH = "C:\Ruby22-x64\bin;$Env:PATH"
        $Env:CMAKE_GENERATOR_NAME = "Visual Studio 12 2013 Win64"
      }
  - git submodule update --init
  - cmake . -G "%CMAKE_GENERATOR_NAME%"
  - cmake --build . --config Debug

before_test:
  - gem install grntest
test_script:
  - SET GRN_QUERY_EXPANDER_TSV_SYNONYMS_FILE=%APPVEYOR_BUILD_FOLDER%\test\command\tmp\synonyms.tsv
  - grntest --groonga src\groonga.exe --base-directory test\command test\command\suite
