version: "{build}"
clone_depth: 10

environment:
  matrix:
    - CMAKE_GENERATOR_NAME: "Visual Studio 12 2013"
    - CMAKE_GENERATOR_NAME: "Visual Studio 12 2013 Win64"

install:
  - SET PATH=C:\Ruby22-x64\bin;%PATH%

build_script:
  - git submodule update --init
  - cmake . -G "%CMAKE_GENERATOR_NAME%"
  - cmake --build . --config Debug

notifications:
  - provider: Email
    to:
      - kou@clear-code.com
      - groonga-commit@lists.osdn.me
    on_build_status_changed: true

test: off
before_test:
  - gem install grntest
test_script:
  - grntest --groonga src\groonga.exe --base-directory test\command test\command\suite
