version: "{build}"
clone_depth: 10

platform:
  - x86
  - x64

notifications:
  - provider: Email
    to:
      - kou@clear-code.com
      - groonga-commit@lists.osdn.me
    on_build_status_changed: true

init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
  - tzutil /s "Tokyo Standard Time"
  - choco install -y imdisk-toolkit
  - mkdir tmp
  - imdisk -a -t file -m tmp -o awe -s 1G -p "/fs:ntfs /q /y"

build_script:
  - ps: |
      if ($Env:PLATFORM -eq "x86")
      {
        $Env:PATH = "C:\Ruby22\bin;$Env:PATH"
        $Env:CMAKE_GENERATOR_NAME = "Visual Studio 12 2013"
      }
      else
      {
        $Env:PATH = "C:\Ruby22-x64\bin;$Env:PATH"
        $Env:CMAKE_GENERATOR_NAME = "Visual Studio 12 2013 Win64"
      }
  - git submodule update --init
  - cd vendor
  - ruby download_mecab.rb
  - ruby download_message_pack.rb
  - cd ..
  - cmake . -G "%CMAKE_GENERATOR_NAME%"
      -DCMAKE_INSTALL_PREFIX=c:\groonga
      -DGRN_WITH_BUNDLED_MECAB=yes
      -DGRN_WITH_BUNDLED_MESSAGE_PACK=yes
  - cmake --build . --config Debug
  - cmake --build . --config Debug --target Install

before_test:
  - git clone --depth 1
      https://github.com/groonga/grntest.git
      test\command\grntest
  - cd test\command\grntest
  - bundle install --binstubs=..\bin
  - cd ..\..\..
test_script:
  - ruby test\command\bin\grntest
     --groonga c:\groonga\bin\groonga.exe
     --base-directory test\command
     --reporter mark
     --n-workers 4
     --timeout 60
     test\command\suite
