name: Linux
on:
  - push
  - pull_request
jobs:
  configure:
    name: configure
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install packages
        run: |
          sudo apt update
          sudo apt install -y -V \
            apt-transport-https \
            autoconf-archive \
            automake1.11 \
            autotools-dev \
            bison \
            cmake \
            gettext \
            gnupg \
            libevent-dev \
            libluajit-5.1-dev \
            libmecab-dev \
            libmsgpack-dev \
            lsb-release \
            mecab-naist-jdic \
            python3-pip \
            rapidjson-dev \
            ruby \
            wget \
            zlib1g-dev
      - name: Install Sphinx
        run: |
          sudo pip3 install Sphinx
      - name: Install Bundler
        run: |
          sudo gem install bundler
      - name: Generate configure
        run: |
          ./autogen.sh
      - name: Configure
        run: |
          ./configure \
            --enable-debug \
            --enable-mruby \
            --with-ruby
      - name: Build
        run: |
          make -j$(nproc)
      - name: Test
        run: |
          test/command/run-test.sh
      - name: Install
        run: |
          make install
