name: "Windows MSVC"
on:
  - push
  - pull_request
jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        label:
          - Visual Studio 2019 x64
        include:
          - label: Visual Studio 2019 x64
            architecture: x64
            artifact_name: vs-2019-x64
            cmake_generator: Visual Studio 16 2019
    runs-on: windows-latest
    steps:
      - name: Disable crash dialog
        run: |
          reg add "HKCU\SOFTWARE\Microsoft\Windows\Windows Error Reporting" `
            /v DontShowUI `
            /t REG_DWORD `
            /d 1 `
            /f
      - uses: actions/setup-ruby@master
      - uses: actions/checkout@master
      - name: Update submodules
        run: |
          git submodule update --init --recursive
      - name: Download bundled packages
        run: |
          cd vendor
          ruby download_groonga_normalizer_mysql.rb
          ruby download_lz4.rb
          ruby download_mecab.rb
          ruby download_message_pack.rb
          ruby download_rapidjson.rb
      - name: Generate env.ps1
        run: |
          echo "`$Env:CMAKE_BUILD_PARALLEL_LEVEL = ${Env:NUMBER_OF_PROCESSORS}" >> env.ps1
          $GROONGA_VERSION = (Get-Content base_version)
          if (!("${Env:GITHUB_REF}".StartsWith("refs/tags/"))) {
            $GROONGA_VERSION += "-$(${Env:GITHUB_SHA}.Substring(0, 7))"
          }
          "GRN_VERSION=${GROONGA_VERSION}" | Set-Content version.sh
          $INSTALL_FOLDER = "groonga-${GROONGA_VERSION}-x64-vs2019"
          $INSTALL_PARENT_FOLDER = "インストール"
          $FULL_INSTALL_FOLDER = `
            "${Env:GITHUB_WORKSPACE}\${INSTALL_PARENT_FOLDER}\${INSTALL_FOLDER}"
          echo "`$INSTALL_FOLDER = `"${INSTALL_FOLDER}`"" >> env.ps1
          echo "`$FULL_INSTALL_FOLDER = `"${FULL_INSTALL_FOLDER}`"" >> env.ps1
          Get-Content env.ps1
      - name: Install Apache Arrow
        run: |
          . .\env.ps1
          New-Item ..\apache-arrow-build -ItemType Directory
          cmake `
            -S vendor\apache-arrow-source\cpp `
            -B ..\apache-arrow-build `
            -A ${{ matrix.architecture }} `
            -G "${{ matrix.cmake_generator }}" `
            "-DCMAKE_INSTALL_PREFIX=${FULL_INSTALL_FOLDER}" `
            -DCMAKE_BUILD_TYPE=Release
          cmake --build ..\apache-arrow-build --config Release
          cmake --build ..\apache-arrow-build --config Release --target Install
      - name: Install Groonga
        run: |
          . .\env.ps1
          New-Item ..\groonga-build -ItemType Directory
          cmake `
            -S . `
            -B ..\groonga-build `
            -A ${{ matrix.architecture }} `
            -G "${{ matrix.cmake_generator }}" `
            "-DCMAKE_INSTALL_PREFIX=${FULL_INSTALL_FOLDER}" `
            -DCMAKE_BUILD_TYPE=ReWithDebInfo `
            -DGRN_WITH_APACHE_ARROW=yes
          cmake --build ..\groonga-build --config RelWithDebInfo
          cmake --build ..\groonga-build --config RelWithDebInfo --target Install
      - name: Prepare artifacts
        run: |
          . .\env.ps1
          New-Item ..\packages -ItemType Directory
          pushd "${FULL_INSTALL_FOLDER}\.."
          Compress-Archive `
            -Path ${INSTALL_FOLDER} `
            -DestinationPath "${Env:GITHUB_WORKSPACE}\..\packages\${INSTALL_FOLDER}.zip"
          popd
      - uses: actions/upload-artifact@master
        with:
          name: ${{ matrix.artifact_name }}
          path: ..\packages
